project:
  type: website

website:
#  title: false
  navbar:
    background: primary
    left:
      - href: index.Rmd
      - href: island.Rmd
      - href: klimatoloogia.Rmd
      - href: maateaduse-tarkvaraline-baas.qmd
      - href: about.Rmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

reference-location: margin
citation-location: margin
