---
title: "Island"
author: 'peacecop kalmer:'
date: "11/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r cars}
library(tibble)
dailyMeans = data.frame("Kuu" = c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"),
                        "Temperatuur" = c(1.24, 1.29, 1.28, 2.42, 4.89, 8.09, 9.69, 9.64, 7.81, 4.94, 2.34, .44),
                        "Sademed" = c(142.54, 157.05, 96.66, 93.23, 62.75, 48.42, 73.1, 100.87, 152.51, 136.85, 116.54, 144.2))
dailyMeans[c("Temperatuur")] = lapply(dailyMeans[c("Temperatuur")], function(dailyMean) {
  dailyMean + 273.15
})
dailyMeans
library(ggplot2)
chart = ggplot(data = dailyMeans, aes(x = Kuu, y = Temperatuur))
chart +
  labs(title="Õhutemperatuur ja sademete kogus Austurlandis", x = "Kuu", y = "Temperatuur (K)")+
  scale_y_continuous(limits = c(273, 283))
library(plotly)
plotly::plot_ly(dailyMeans, x = ~Kuu, y = ~Temperatuur, type = "bar", name = "Temperatuurid", text = ~Temperatuur) %>%
  add_trace(x = ~Kuu, y = ~Sademed, type="scatter", mode = "lines", yaxis = "y2", name = "Sademeid") %>%
  add_text (y = dailyMeans$Sademed, yaxis = "y2", text = ~Sademed, showlegend = FALSE) %>%
  layout(yaxis = list(range = c(273, 283), title = "Temperatuur (K)"), yaxis2 = list(range = c(0, 160), overlaying = "y", side = "right", title = "Sademed (mm)"))
```

```{r}
library(sf)
library(spData)
country = world[world$name_long == "Iceland", ]
geometry = st_geometry(country)
geometry
library(ggplot2)
wr <- map_data("world", region = c("Iceland"))
library(emojifont)
plotOfIceland = ggplot() +
  geom_map(aes(map_id = region), map = wr, data = wr, colour = "#008b52", fill = "#008b52", size = 0) +
  expand_limits(x = wr$long, y = wr$lat) + 
  theme_void() + 
  # What?
  geom_text(data = data.frame(lon = -16.332083, lat = 64.951083), aes(x = lon, y = lat), family = "EmojiOne", label = "\U1F6E3", size = 16, vjust = .2, color = "#ffffff") +
  #geom_rect(data = data.frame(lon = -16.332083, lat = 64.951083), aes(xmin = lon - 5, xmax = lon + .5, 
    #ymin = lat - .2, ymax = lat + .2), fill = "transparent") +
  # Where?
  geom_text(data = data.frame(lon = -15, lat = 63.7), aes(x = lon, y = lat), family = "EmojiOne", label = "\U1F310", size = 16, vjust = .2, color = "#DC1E35") +
  # Geology
  geom_text(data = data.frame(lon = -14, lat = 65.9), aes(x = lon, y = lat), family = "EmojiOne", label = "\U1F3d7", size = 16, vjust = .2, color = "#DC1E35") +
  # Plants
  geom_text(data = data.frame(lon = -21, lat = 66), aes(x = lon, y = lat), family = "EmojiOne", label = "\U1F331", size = 16, vjust = .2, color = "#DC1E35") +
  # Animals
  geom_text(data = data.frame(lon = -23, lat = 64.5), aes(x = lon, y = lat), family = "EmojiOne", label = "\U1F40e", size = 16, vjust = .2, color = "#DC1E35") +
  # Human activities
  geom_text(data = data.frame(lon = -23.7, lat = 64), aes(x = lon, y = lat), family = "EmojiOne", label = "\U1F477", size = 16, vjust = .2, color = "#DC1E35") +
  # Climate
  geom_text(data = data.frame(lon = -14.4, lat = 64.1), aes(x = lon, y = lat), family = "EmojiOne", label = "\U1F326", size = 16, vjust = .2, color = "#DC1E35") +
  # Currents
  geom_text(data = data.frame(lon = -16.3, lat = 63.7), aes(x = lon, y = lat), family = "EmojiOne", label = "\U1F30a", size = 16, vjust = .2, color = "#DC1E35") +
  # Soil
  geom_text(data = data.frame(lon = -23.5, lat = 65.2), aes(x = lon, y = lat), family = "EmojiOne", label = "\U1F30b", size = 16, vjust = .2, color = "#DC1E35")
 # geom_point(data = data.frame(lon = -16.332083, lat = 64.951083), aes(x = lon, y = lat))
plotOfIceland
ggsave(file="iceland.svg", plot=plotOfIceland)
```

